export const FETCH_KARYAWAN = "FETCH_KARYAWAN"; 
export const GET_ONE_KARYAWAN = "GET_ONE_KARYAWAN"; 
export const GET_ONE_KARYAWAN_EMAIL = "GET_ONE_KARYAWAN_EMAIL"; 
export const ADD_KARYAWAN = "ADD_KARYAWAN"; 
export const EDIT_KARYAWAN = "EDIT_KARYAWAN"; 
export const DELETE_KARYAWAN = "DELETE_KARYAWAN"; 

export const FETCH_PRESENSI = "FETCH_PRESENSI";
export const PUSH_CLOCK = "PUSH_CLOCK";
export const EDIT_PRESENSI = "EDIT_PRESENSI";

export const FETCH_GAJI = "FETCH_GAJI";
export const GET_ONE_GAJI = "GET_ONE_GAJI"; 
export const ADD_GAJI = "ADD_GAJI"; 
export const EDIT_GAJI = "EDIT_GAJI"; 
export const DELETE_GAJI = "DELETE_GAJI"; 

export const LOGIN = "LOGIN";

export const FETCH_LEMBUR = "FETCH_LEMBUR";
export const ADD_LEMBUR = "ADD_LEMBUR"; 
export const GET_ONE_LEMBUR = "GET_ONE_LEMBUR"; 
export const EDIT_LEMBUR = "EDIT_LEMBUR";

export const FETCH_CUTI = "FETCH_CUTI";
export const ADD_CUTI = "ADD_CUTI"; 
export const GET_ONE_CUTI = "GET_ONE_CUTI"; 
export const EDIT_CUTI = "EDIT_CUTI";

export const FETCH_REIMBURSEMENT = "FETCH_REIMBURSEMENT";
export const ADD_REIMBURSEMENT = "ADD_REIMBURSEMENT"; 
export const GET_ONE_REIMBURSEMENT = "GET_ONE_REIMBURSEMENT"; 
export const EDIT_REIMBURSEMENT = "EDIT_REIMBURSEMENT";

export const FETCH_GOLONGAN = "FETCH_GOLONGAN";
export const GET_ONE_GOLONGAN = "GET_ONE_GOLONGAN";
export const ADD_GOLONGAN = "ADD_GOLONGAN"; 
export const DELETE_GOLONGAN = "DELETE_GOLONGAN"; 
export const EDIT_GOLONGAN = "EDIT_GOLONGAN";

export const FETCH_PROJECT = "FETCH_PROJECT";
export const GET_ONE_PROJECT = "GET_ONE_PROJECT";
export const ADD_PROJECT = "ADD_PROJECT"; 
export const EDIT_PROJECT = "EDIT_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";

export const FETCH_PERFORMA = "FETCH_PERFORMA";
export const GET_ONE_PERFORMA = "GET_ONE_PERFORMA";
export const ADD_PERFORMA = "ADD_PERFORMA"; 
export const EDIT_PERFORMA = "EDIT_PERFORMA";
export const DELETE_PERFORMA = "DELETE_PERFORMA";

export const FETCH_INFO = "FETCH_INFO";
export const GET_ONE_INFO = "GET_ONE_INFO";
export const ADD_INFO = "ADD_INFO"; 
export const EDIT_INFO = "EDIT_INFO";
export const DELETE_INFO = "DELETE_INFO";